[project]
name = "GoogleImages"
version = "1.0.0"
description = "Search Google images"

[[binaries]]
name = "google_images"
path = "main.py"
default = true

[python]
interpreter = { version = "3.9", implementation = "cpython" }

[build]
output-dir = "dist/"